### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by TheBrankman** [CreasolTech/domoticz-hyundai-kia#1]
Hello,

I have a Kia e-Niro, 2021 and at home I have Domoticz running on a Raspberry Pi.

I am trying to install the domoticz-hyndai-kia plugin as described in the staps. I can find the plugin in the "hardware" tab, but for some reason it is not loaded and I cannot find any of the devices.

Raspberry: Pi B+
OS: Version 11, Bullseye
Domoticz: 2022.1

This I have found in the Domoticz log:

![DomoticzErrorLog](https://user-images.githubusercontent.com/81829287/161985787-35c81a2b-f23d-4a0b-8a7d-8bea05bb20fb.png)

I have found several forum posts about such kind of error, but I can not solve it.
Is there someone who can help me?
Sorry if it is because of my lack of knowledge!

**Comment by CreasolTech** [comment]
Hi, 
the python dateutil module is missing.
`sudo apt install python3-dateutil`

**Comment by TheBrankman** [comment]
@CreasolTech

 Tnx for your quick reply! That solved the error! The logfile does show several entries of the plugin.
![KIA2](https://user-images.githubusercontent.com/81829287/161990837-ac85694a-2a86-4259-9979-232936eb85a3.png)

I have added the hardware:
![hardware](https://user-images.githubusercontent.com/81829287/161990716-a81601b0-02d7-45fa-94db-877d14ae5440.png)

But still not see any devices? Am I still missing something? (The devices with Idx 31 to 36 are devices which are attached to a kWh meter).
![devices](https://user-images.githubusercontent.com/81829287/161991129-f1c6ac09-5f1e-4196-b9a8-49d88bdad90b.png)

**Comment by TheBrankman** [comment]
Maybe interesting logs:
![log](https://user-images.githubusercontent.com/81829287/161991492-3ff8892f-b7f2-4262-9e86-bc2cec9de6ae.png)

**Comment by CreasolTech** [comment]
Contact me by Telegram, nickname CreasolTech

**Comment by westd999** [comment]
Hi there,

Since a few days I have a KIA Xceed PHEV and was supprised to see that there is already a plugin to integrate the KIA Connect app features in Domoticz. Nice work.
I have updated Python to 3.9.13 and installed the plugin. Although Domoticz refuses to load the plugin. I got the following error:

![image](https://user-images.githubusercontent.com/26147910/174644104-e816750f-0f60-4541-80df-9096895a85df.png)

Someone with the same error and knows a sollution.
I can't figure this out.

**Comment by CreasolTech** [comment]
As you can see in the domoticz log, domoticz is using python 3.7: I'm not sure this can be a problem, but I know that the lib hyundai_kia_connect_api is a bit critical. Maybe updating domoticz to the beta version helps (don't worry, beta version is stable like a debian testing!!)

**Comment by westd999** [comment]
I will update Domoticz to the latest beta and try again, thanks

**Comment by westd999** [comment]
Hi CreasolTech,
I upgraded to Bullseye and the latest Domoticz. beta. Domoticz is now using Python 3.9.2. Plugin starts but crashes immediately, No new devices were made (and allow new devices is ON).
Any idea ?
John

2022-06-23 18:51:57.611 KIA Connect: Worker thread started.
2022-06-23 18:51:57.611 Status: KIA Connect: Entering work loop.
2022-06-23 18:51:57.611 Status: KIA Connect: Started.
2022-06-23 18:51:59.168 Status: KIA Connect: Initialized version 1.0.5, author 'CreasolTech'
2022-06-23 18:52:07.086 KIA Connect: check_and_refresh_token()...
2022-06-23 18:52:27.872 Error: KIA Connect: Call to function 'onHeartbeat' failed, exception details:
2022-06-23 18:52:27.879 Error: KIA Connect: Traceback (most recent call last):
2022-06-23 18:52:27.879 Error: KIA Connect: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 592, in onHeartbeat
2022-06-23 18:52:27.879 Error: KIA Connect: _plugin.onHeartbeat()
2022-06-23 18:52:27.879 Error: KIA Connect: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 178, in onHeartbeat
2022-06-23 18:52:27.879 Error: KIA Connect: ret=self.vm.check_and_refresh_token()
2022-06-23 18:52:27.879 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
2022-06-23 18:52:27.879 Error: KIA Connect: self.initialize()
2022-06-23 18:52:27.879 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
2022-06-23 18:52:27.879 Error: KIA Connect: self.update_all_vehicles_with_cached_state()
2022-06-23 18:52:27.879 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
2022-06-23 18:52:27.879 Error: KIA Connect: self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
2022-06-23 18:52:27.879 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
2022-06-23 18:52:27.879 Error: KIA Connect: self.api.update_vehicle_with_cached_state(self.token, vehicle)
2022-06-23 18:52:27.879 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 295, in update_vehicle_with_cached_state
2022-06-23 18:52:27.880 Error: KIA Connect: dc = [ x['targetSOClevel'] for x in target_soc_list if x['plugType'] == 0 ][-1],
2022-06-23 18:52:27.880 Error: KIA Connect: TypeError: 'NoneType' object is not iterable

**Comment by CreasolTech** [comment]
I suggest to remove the hyundai_kia_connect_api library, then load that lib using the commands:
```
cd  /usr/local/src
git clone https://github.com/jwefers/hyundai_kia_connect_api
mv /usr/local/lib/python3.9/hyundai_kia_connect_api /var/tmp 2>/dev/null
ln -s /usr/local/src/hyundai_kia_connect_api/hyundai_kia_connect_api /usr/local/lib/python3.9/hyundai_kia_connect_api

#remove __pycache__ dir from the lib (it contains the __pycache__ with sources compiled by a different python version or different CPU)
for d in /usr/local/lib/python3*; do find $d -name __pycache__ -exec rm -r {} \; ; done
```

Please keep us informed.

**Comment by westd999** [comment]
Hi Creasol, I did install the library on the right place but no progres. Which version of Domoticz on which OS and which version of Python you use?
Also other plugins produce errors now, so there is also something wrong with the Domoticz / Python, thanks in advance

**Comment by CreasolTech** [comment]
Domoticz: last beta 14352, but also works with 14318
Python 3.9.2
And you? If you need me to check your installation, contact me by Telegram @CreasolTech (I need ssh or anydesk access)

**Comment by westd999** [comment]
Hi, Domoticz is latest beta, python 3.9.3, bit I can't test or search for a solution the next 3 weeks because I am on holiday

**Comment by CreasolTech** [comment]
> Hi, Domoticz is latest beta, python 3.9.3, bit I can't test or search for a solution the next 3 weeks because I am on holiday

How can you go on holiday without monitoring your car??? ;-)
Keep us informed, when you'll come back! I wish you nice a holiday!

**Comment by westd999** [comment]
Hi,
Back form holiday, monitored the car via the standard app :-)

I took another Raspberry with a fresh OS Lite (Bullseye) and compiled domoticz from source. Same issues as before. See this log:

2022-07-17 13:48:13.743 Error: KIA Connect: (domoticz-hyundai-kia) failed to load 'plugin.py', Python Path used was '/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2022-07-17 13:48:13.744 Error: KIA Connect: Traceback (most recent call last):
2022-07-17 13:48:13.744 Error: KIA Connect: File "/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 69, in <module>
2022-07-17 13:48:13.744 Error: KIA Connect: from hyundai_kia_connect_api import *
2022-07-17 13:48:13.744 Error: KIA Connect: ModuleNotFoundError: No module named 'hyundai_kia_connect_api'

That the enhanced module was not found has to do with the defined path python uses. I don't know how to fix that so I removed the hyundai_kia_connect_api symlink, directory's etc. and installed the standard hyundai_kia_connect_api module with PIP3. After a reboot there was another module not found. See this log:

2022-07-17 14:00:54.621 Error: KIA Connect: (domoticz-hyundai-kia) failed to load 'plugin.py', Python Path used was '/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2022-07-17 14:00:54.625 Error: KIA Connect: Traceback (most recent call last):
2022-07-17 14:00:54.625 Error: KIA Connect: File "/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 69, in <module>
2022-07-17 14:00:54.625 Error: KIA Connect: from hyundai_kia_connect_api import *
2022-07-17 14:00:54.625 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/__init__.py", line 3, in <module>
2022-07-17 14:00:54.625 Error: KIA Connect: from .ApiImpl import ApiImpl, ClimateRequestOptions
2022-07-17 14:00:54.625 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 9, in <module>
2022-07-17 14:00:54.625 Error: KIA Connect: from .Vehicle import Vehicle, EvChargeLimits
2022-07-17 14:00:54.625 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/Vehicle.py", line 7, in <module>
2022-07-17 14:00:54.625 Error: KIA Connect: import pytz
2022-07-17 14:00:54.625 Error: KIA Connect: ModuleNotFoundError: No module named 'pytz'

After installing pytz with PIP3 the plugin runs for a few minutes, al necessary modules where found, but crashes after a few minutes with following error:

2022-07-17 14:06:59.879 KIA Connect: Worker thread started.
2022-07-17 14:06:59.880 Status: KIA Connect: Started.
2022-07-17 14:06:59.879 Status: KIA Connect: Entering work loop.
2022-07-17 14:06:59.880 Status: NotificationSystem: thread started...
2022-07-17 14:06:59.880 Status: EventSystem: reset all events...
2022-07-17 14:06:59.881 Status: EventSystem: reset all device statuses...
2022-07-17 14:07:00.024 Status: Python EventSystem: Initializing event module.
2022-07-17 14:07:00.024 Status: EventSystem: Started
2022-07-17 14:07:00.025 Status: EventSystem: Queue thread started...
2022-07-17 14:07:00.302 Status: PluginSystem: 1 plugins started.
2022-07-17 14:07:01.040 Status: KIA Connect: Initialized version 1.0.5, author 'CreasolTech'
2022-07-17 14:07:09.058 KIA Connect: check_and_refresh_token()...
2022-07-17 14:07:26.574 Error: KIA Connect: Call to function 'onHeartbeat' failed, exception details:
2022-07-17 14:07:26.583 Error: KIA Connect: Traceback (most recent call last):
2022-07-17 14:07:26.583 Error: KIA Connect: File "/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 592, in onHeartbeat
2022-07-17 14:07:26.583 Error: KIA Connect: _plugin.onHeartbeat()
2022-07-17 14:07:26.583 Error: KIA Connect: File "/home/pi/dev-domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 178, in onHeartbeat
2022-07-17 14:07:26.583 Error: KIA Connect: ret=self.vm.check_and_refresh_token()
2022-07-17 14:07:26.583 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
2022-07-17 14:07:26.583 Error: KIA Connect: self.initialize()
2022-07-17 14:07:26.583 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
2022-07-17 14:07:26.584 Error: KIA Connect: self.update_all_vehicles_with_cached_state()
2022-07-17 14:07:26.584 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
2022-07-17 14:07:26.584 Error: KIA Connect: self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
2022-07-17 14:07:26.584 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
2022-07-17 14:07:26.584 Error: KIA Connect: self.api.update_vehicle_with_cached_state(self.token, vehicle)
2022-07-17 14:07:26.584 Error: KIA Connect: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 295, in update_vehicle_with_cached_state
2022-07-17 14:07:26.584 Error: KIA Connect: dc = [ x['targetSOClevel'] for x in target_soc_list if x['plugType'] == 0 ][-1],
2022-07-17 14:07:26.584 Error: KIA Connect: TypeError: 'NoneType' object is not iterable

No devices were created in the device tab (it is allowed) and I don't know how to force that.
Any solution ?

Best regards,
John

**Comment by CreasolTech** [comment]
> ModuleNotFoundError: No module named 'hyundai_kia_connect_api'

Hi John, 
did you follow the instructions to install the module? Maybe typing the command to install the hyundai_kia_connect_api you get an error! In this case please let me know, so I can fix the instructions.
```
#become root user
sudo su -

#install git, if not already installed
which git
if [ $? -ne 0 ]; then sudo apt install git; fi

#change to the domoticz directory / plugins
cd /home/pi/domoticz/plugins 

#fetch the Python Plugin Manager (that can be used to install/upgrade other plugins, including domoticz-hyundai-kia)
git clone https://github.com/ycahome/pp-manager

#install python3-dateutil
sudo apt install python3-dateutil

#install original hyundai-kia-connect-api lib 
# pip3 install hyundai-kia-connect-api
#instead of the original version, install the version enhanced by jwefers
cd  /usr/local/src
git clone https://github.com/jwefers/hyundai_kia_connect_api
mv /usr/local/lib/python3.9/hyundai_kia_connect_api /var/tmp 2>/dev/null
ln -s /usr/local/src/hyundai_kia_connect_api/hyundai_kia_connect_api /usr/local/lib/python3.9/hyundai_kia_connect_api

#return on previous directory
cd -

#remove __pycache__ dir from the lib (it contains the __pycache__ with sources compiled by a different python version or different CPU)
for d in /usr/local/lib/python3*; do find $d -name __pycache__ -exec rm -r {} \; ; done

#fetch Creasol Plugin

git clone https://github.com/CreasolTech/domoticz-hyundai-kia

#restart Domoticz daemon
service domoticz restart
```

**Comment by westd999** [comment]
Hi,
I installed everything exactly as described. No errors during installation.
Is there a way to force the creation of the hardware devices in Domoticz ?
Best regards,
John

**Comment by CreasolTech** [comment]
As you reported in your previous message, you have a problem installing the python **hyundai_kia_connect_api** module: you installed it by using the pip3 command, ok.
Now you have the error **ModuleNotFoundError: No module named 'pytz'** , that you can fix by issuing the command
**apt install python3-tz** or **pip3 install pytz**
Please let me know: in case of problem, please contact me by Telegram, nickname CreasolTech

**Comment by westd999** [comment]
Oh, sorry, indeed, when installing the enhanced hyundai_kia_connect_api module the python script can't find it. When installing the standaard hyundai_kia_connect_api module with PIP3 it is OK, after installing the pytz module with PIP3, also that module is found

Creasol ***@***.***> schreef op 19 juli 2022 15:47:01 CEST:
>As you reported in your previous message, you have a problem installing the python **hyundai_kia_connect_api** module: you installed it by using the pip3 command, ok.
>Now you have the error **ModuleNotFoundError: No module named 'pytz'** , that you can fix by issuing the command
>**apt install python3-tz** or **pip3 install pytz**
>Please let me know: in case of problem, please contact me by Telegram, nickname CreasolTech
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/CreasolTech/domoticz-hyundai-kia/issues/1#issuecomment-1189076229
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by westd999** [comment]
Hi Creasol,

Last evening I managed it to get a working plugin :-). There are still some issues related to Domoticz and Bullseye. Devices are not shown in the device tab (device list is empty) but only in the switches and utility tab. When I find some time next weekend I will make a fresh install of Domoticz with Buster and the plugin. On some forums that is the advise to get a stable Domoticz installation.

To get it working I deleted the standard hyundai_kia_connect_api module (installed via PIP3) and manually copied the enhanced hyundai_kia_connect_api module in the /usr/local/lib/python3.9/dist-packages directory. That's the same directory PIP3 installes the standard module. 
Is there a special reason why you install the hyundai_kia_connect_api module in /usr/local/src and make a symlink in /usr/local/lib/python3.9 ?
On my fresh installed Domoticz/Bullseye Pi the /usr/local/lib/python3.9 directory is not in the path python uses, so he can't find the module, nor via the symlink.
I didn't change the python path to test if it works with your installation method in the usr/local/src directory and the symlink. That could be a solution. Another solution is to install the module in the  /usr/local/lib/python3.9/dist-packages directory what I did. 
Maybe that it is not the right directory ment for additional "self made" modules. But it works.
I will keep you informed about my findings next weekend.
Best regards,
John

**Comment by CreasolTech** [comment]
> Is there a special reason why you install the hyundai_kia_connect_api module in /usr/local/src and make a symlink in /usr/local/lib/python3.9 ?

No, there isn't a reason to do that.
In my experience, the hyundai_kia_connect_api has several troubles so I tried different branches and patches for that module by using the command `git clone module_repository_url` and then checking it.
If you install it using git, you'll get a hyundai_kia_connect_api directory within another hyundai_kia_connect_api subdir containing the python module: this is essentially the reason why I choose to get the git-hub repository in /usr/local/src and then make a symlink from /usr/local/lib/python3.9/dist-packages to /usr/local/src/hyundai_kia_connect_api/hyundai_kia_connect_api

Most probably if you followed my instructions step by step, installing the module using git, it would work also with Debian Bullseye.
In any case you will expect some bad behavious: sometimes the connection to the car will not work, sometimes it generates a segmentation fault needing Domoticz to be restarted.
I hope that the hyundai_kia_connect_api module will be improved soon.

**Comment by TheBrankman** [comment]
I have re-installed my Domoticz and would like to add this Hyundai-Kia addin again.
I added it manually and with the plugin manager.

In bith cases the Hyundai-Kia addin will not load. 
I have Python 3.9 with Domoticz beta.
The Kia hardware is visible and added, but no devices....

This is what the plugin sais after Domoticz reboot:
`2022-09-08 13:27:21.998 Error: Kia: (domoticz-hyundai-kia) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/HyundaiKiaConnect/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2022-09-08 13:27:22.011 Error: Kia: Traceback (most recent call last):
2022-09-08 13:27:22.011 Error: Kia: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 69, in <module>
2022-09-08 13:27:22.011 Error: Kia: from hyundai_kia_connect_api import *
2022-09-08 13:27:22.011 Error: Kia: ModuleNotFoundError: No module named 'hyundai_kia_connect_api'`

**Comment by CreasolTech** [comment]
You have to follows all installation steps, including the installation of the hyundai-kia-connect-api python library
You have a list of command to write to install everything: types also the commands to install the lib!
In case of troubles, you can write here!

**Comment by westd999** [comment]
Hi TheBrankman,
I had similar problems and copied the hyundai_kia_connect_api directory in this map: /usr/local/lib/python3.9/dist-packages, That map is one of the maps Domoticz is looking for modules. I also had to install pytz with pip3 because the plugin couldn't find pytz.
I also added "sys.path.append('/usr/local/lib/python3.9/site-packages')" in /home/pi/domoticz/plugins/domoticz-hyundai-kia/plugin.py. I can't remember for wich error that was. Mayby this helps on your system.
Suc6

**Comment by CreasolTech** [comment]
Normally it's not needed to add "sys.path.append(..." because that path is enabled by default.
Carefully must be taken when installing the hyundai-kia-connect-api lib because inside the main directory there is another subdir with the same name: only the subdir should be moved (or linked, as done in my instructions) to /usr/local/lib/python3.9/site-packages
