### ISSUE TITLE
Commands not send to vehicle (EV6)

### ISSUE THREAD

**Issue by bobbesnl** [CreasolTech/domoticz-hyundai-kia#13]
Hi all,
First of all, nice piece of software!!
I own a KIA EV6. Since last update it finally connects to KIA Connect and get all the vehicle info. But when I try to change a value (AC or DC charge percentage) or when I want to turn on defreezing/airco then there is a error message in the logs. Can I fix it myself?
Thanks in advance!

```
2023-12-18 08:21:10.537 KIA: onCommand(Unit=223, Command=Set Level, Level=100, Hue=)
2023-12-18 08:21:10.537 KIA: Device Name=KIA EV6 Charge limit AC
2023-12-18 08:21:10.524 Status: User: Admin (IP: 192.168.1.53) initiated a switch command (172/KIA EV6 Charge limit AC/Set Level)
2023-12-18 08:21:10.539 Error: KIA: Call to function 'onCommand' failed, exception details:
2023-12-18 08:21:10.541 Error: KIA: Traceback (most recent call last):
2023-12-18 08:21:10.541 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 969, in onCommand
2023-12-18 08:21:10.541 Error: KIA: _plugin.onCommand(Unit, Command, Level, Hue)
2023-12-18 08:21:10.541 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 317, in onCommand
2023-12-18 08:21:10.541 Error: KIA: vehicleId=self.getVehicleId(Unit) # get name and id for the vehicle
2023-12-18 08:21:10.541 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 150, in getVehicleId
2023-12-18 08:21:10.541 Error: KIA: name=re.findall(f"{Parameters['Name']} - ([a-zA-Z0-9-_]+) .*", Devices[Unit].Name)[0]
2023-12-18 08:21:10.541 Error: KIA: IndexError: list index out of range
2023-12-18 08:21:13.760 KIA: onCommand(Unit=224, Command=Set Level, Level=80, Hue=)
2023-12-18 08:21:13.760 KIA: Device Name=KIA EV6 Charge limit DC
2023-12-18 08:21:13.751 Status: User: Admin (IP: 192.168.1.53) initiated a switch command (173/KIA EV6 Charge limit DC/Set Level)
2023-12-18 08:21:13.760 Error: KIA: Call to function 'onCommand' failed, exception details:
2023-12-18 08:21:13.761 Error: KIA: Traceback (most recent call last):
2023-12-18 08:21:13.761 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 969, in onCommand
2023-12-18 08:21:13.761 Error: KIA: _plugin.onCommand(Unit, Command, Level, Hue)
2023-12-18 08:21:13.761 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 317, in onCommand
2023-12-18 08:21:13.761 Error: KIA: vehicleId=self.getVehicleId(Unit) # get name and id for the vehicle
2023-12-18 08:21:13.761 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 150, in getVehicleId
2023-12-18 08:21:13.761 Error: KIA: name=re.findall(f"{Parameters['Name']} - ([a-zA-Z0-9-_]+) .*", Devices[Unit].Name)[0]
2023-12-18 08:21:13.761 Error: KIA: IndexError: list index out of range

2023-12-18 08:28:12.637 KIA: onCommand(Unit=206, Command=On, Level=0, Hue=)
2023-12-18 08:28:12.638 KIA: Device Name=KIA EV6 ontdooien
2023-12-18 08:28:12.625 Status: User: Admin (IP: 192.168.1.53) initiated a switch command (182/KIA EV6 ontdooien/On)
2023-12-18 08:28:12.638 Error: KIA: Call to function 'onCommand' failed, exception details:
2023-12-18 08:28:12.638 Error: KIA: Traceback (most recent call last):
2023-12-18 08:28:12.638 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 969, in onCommand
2023-12-18 08:28:12.638 Error: KIA: _plugin.onCommand(Unit, Command, Level, Hue)
2023-12-18 08:28:12.638 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 317, in onCommand
2023-12-18 08:28:12.638 Error: KIA: vehicleId=self.getVehicleId(Unit) # get name and id for the vehicle
2023-12-18 08:28:12.639 Error: KIA: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 150, in getVehicleId
2023-12-18 08:28:12.639 Error: KIA: name=re.findall(f"{Parameters['Name']} - ([a-zA-Z0-9-_]+) .*", Devices[Unit].Name)[0]
2023-12-18 08:28:12.639 Error: KIA: IndexError: list index out of range
```

**Comment by CreasolTech** [comment]
Hi, 

thanks for the feedback.

I have improved the documentation a little bit: please read the README file in the project homepage and rename the devices as originals.

Below the description of the problem, but you can read better in the README file that contains bold texts.

=================================================================================


Before activating this plugin, assure that you've set the right name to your car (through the Hyundai/Kia connect app) short and simple: that name is used to identify devices in Domoticz. Also, use a very short name for the hardware plugin.

When plugin is activated, more than 30 devices will be automatically added to domoticz, named as {PLUGIN_NAME} - {VEHICLE_NAME} {device name}

If you want to rename a device, change only the {device name} part, do not change the {PLUGIN_NAME} - {VEHICLE_NAME} part of device name because it's used by the plugin to associate device name to a vehicle_name and vehicle_id provided by the cloud. Also, do not change the name of the ODOMETER device: leave this device name as original!

**Comment by bobbesnl** [comment]
I did rename some devices indeed. The problem is solved after I removed the plugin from domoticz, updated the plugin (I saw you changed also some code) and restarted domoticz. Then added the plugin again without renaming anything. Now it is working!
Thank you and keep up the good work!
