### ISSUE TITLE
When running domoticz as non root user, no access to log file error:  PermissionError: [Errno 13] Permission denied: '/var/log/domoticz.log'

### ISSUE THREAD

**Issue by bobbesnl** [CreasolTech/domoticz-hyundai-kia#17]
So I'm testing because of issue #15 and I saw another error, which I saw also several months back but did not mention it here because I created a workaround for it.

When running domoticz as a non-root user then the plugin has no right to write to log file in /var/log/domoticz.log

2024-04-03 22:12:50.441 Status: Hyundai: Entering work loop.
2024-04-03 22:12:50.441 Status: Hyundai: Started.
2024-04-03 22:12:50.441 Status: NotificationSystem: thread started...
2024-04-03 22:12:50.442 Status: EventSystem: reset all events...
2024-04-03 22:12:50.442 Status: EventSystem: reset all device statuses...
2024-04-03 22:12:50.465 Status: Python EventSystem: Initializing event module.
2024-04-03 22:12:50.465 Status: EventSystem: Started
2024-04-03 22:12:50.465 Status: EventSystem: Queue thread started...
2024-04-03 22:12:50.762 Status: Hyundai: Initialized version 1.1.5, author 'CreasolTech, WillemD61'
2024-04-03 22:12:50.923 Status: PluginSystem: 1 plugins started.
2024-04-03 22:12:50.764 Error: Hyundai: Call to function 'onStart' failed, exception details:
2024-04-03 22:12:50.764 Error: Hyundai: Traceback (most recent call last):
2024-04-03 22:12:50.764 Error: Hyundai: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 1057, in onStart
2024-04-03 22:12:50.764 Error: Hyundai: _plugin.onStart()
2024-04-03 22:12:50.764 Error: Hyundai: File "/home/bbossink/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 210, in onStart
2024-04-03 22:12:50.764 Error: Hyundai: logging.basicConfig(filename='/var/log/domoticz.log', encoding='utf-8', level=logging.INFO)
2024-04-03 22:12:50.764 Error: Hyundai: File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
2024-04-03 22:12:50.764 Error: Hyundai: h = FileHandler(filename, mode,
2024-04-03 22:12:50.764 Error: Hyundai: File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
2024-04-03 22:12:50.764 Error: Hyundai: StreamHandler.__init__(self, self._open())
2024-04-03 22:12:50.764 Error: Hyundai: File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
2024-04-03 22:12:50.764 Error: Hyundai: return open_func(self.baseFilename, self.mode,
2024-04-03 22:12:50.764 Error: Hyundai: PermissionError: [Errno 13] Permission denied: '/var/log/domoticz.log'
2024-04-03 22:13:20.065 Hyundai: *** check_and_refresh_token()...
2024-04-03 22:13:21.990 Hyundai: *** check_and_force_update_vehicles(300)...

No errors when running as root.

Workaround:
at startup of domoticz run a script to set correct permissions:

#!/bin/bash
sudo chmod 777 /var/log
touch /var/log/domoticz.log
sudo chmod 666 /var/log/domoticz.log

**Comment by bobbesnl** [comment]
Changed code in line #210 and #211:

old:
```
logging.basicConfig(filename='/var/log/domoticz.log', encoding='utf-8', level=logging.INFO)
#logging.basicConfig(filename='/var/log/domoticz.log', encoding='utf-8', level=logging.DEBUG) #DEBUG
```

new:
```
logging.basicConfig(filename='/var/tmp/domoticz.log', encoding='utf-8', level=logging.INFO)
#logging.basicConfig(filename='/var/tmp/domoticz.log', encoding='utf-8', level=logging.DEBUG) #DEBUG
```


This is working for me on Ubuntu 22.04 installation and Raspberry pi Debian version 11 (Bullseye)

Is it possible for you to change that in source code, so logging is possible also on systems where domoticz doesn't run under root priveleges? Thanks!

Grtz,
Bas

**Comment by WillemD61** [comment]
I commented out the line totally because python logging is not used in the code anyway. All logging is using Domoticz.Log.
