### ISSUE TITLE
Domoticz error log

### ISSUE THREAD

**Issue by eekhoorn** [CreasolTech/domoticz-hyundai-kia#19]
Hi,
Since a couple of days I'm getting these errors in the domoticz log (running domoticz 2024.build 16081):
`2024-07-04 20:09:44.711 Error: KIA:
2024-07-04 20:09:44.711 Error: KIA: During handling of the above exception, another exception occurred:
2024-07-04 20:09:44.711 Error: KIA:
2024-07-04 20:09:44.711 Error: KIA: Traceback (most recent call last):
2024-07-04 20:09:44.711 Error: KIA: File "/home/pi/domoticz/plugins/domoticz-hyundai-kia/plugin.py", line 1052, in getCounter
2024-07-04 20:09:44.711 Error: KIA: response = requests.get(apiCall)
2024-07-04 20:09:44.711 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
2024-07-04 20:09:44.711 Error: KIA: return request("get", url, params=params, **kwargs)
2024-07-04 20:09:44.711 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
2024-07-04 20:09:44.711 Error: KIA: return session.request(method=method, url=url, **kwargs)
2024-07-04 20:09:44.711 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
2024-07-04 20:09:44.711 Error: KIA: resp = self.send(prep, **send_kwargs)
2024-07-04 20:09:44.711 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
2024-07-04 20:09:44.711 Error: KIA: r = adapter.send(request, **kwargs)
2024-07-04 20:09:44.711 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
2024-07-04 20:09:44.711 Error: KIA: raise ConnectionError(e, request=request)
2024-07-04 20:09:44.711 Error: KIA: requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /json.htm?type=command&param=getdevices&rid=1585 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5feeb430>: Failed to establish a new connection: [Errno 111] Connection refused'))`

I'm running Domoticz not on port 8080, is this causing the problem?

**Comment by CreasolTech** [comment]
Hi, 
please be patient: I'm just rewriting the plugin to use the new DomoticzEx framework. I'll inform you when you can download the new version and retry.
In the meanwhile, check Setup -> Settings -> Security -> API Protection: enable this flag.

**Comment by eekhoorn** [comment]
OK, thank you for your quick response!

**Comment by CreasolTech** [comment]
Hi @eekhoorn 
did you fix the problem by enabling "API protection" flag?

If you want, you can update the plugin. Please note that new devices now must be manually renamed  "VEHICLE_NAME: DEVICE_NAME" : check the README file, Update section.

Please keep me informed for any troubles and suggestions.

**Comment by eekhoorn** [comment]
after the update and using the new devices names I got this message in the error log:

2024-07-06 11:51:42.371 Error: KIA: Trying to get location address, but got response_code 403
2024-07-06 11:51:42.371 URL=https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=16&lat=XXX&lon=YYY

strange, because when I used this URL directly in google it's working..

But, anyway, thanks for your great plugin!

**Comment by CreasolTech** [comment]
Thanks, now it should work.

**Comment by eekhoorn** [comment]
thx again, it's working now!
