### ISSUE TITLE
Domoticz error - running plugin V.2.1

### ISSUE THREAD

**Issue by eekhoorn** [CreasolTech/domoticz-hyundai-kia#20]
Running the latest stable domoticz (2024.6) and plugin V2.1 I got the following error:
`2024-07-14 21:10:48.082 Error: KIA:
2024-07-14 21:10:48.082 Error: KIA: The above exception was the direct cause of the following exception:
2024-07-14 21:10:48.082 Error: KIA:
2024-07-14 21:10:48.082 Error: KIA: Traceback (most recent call last):
2024-07-14 21:10:48.082 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-07-14 21:10:48.082 Error: KIA: response = self._make_request(
2024-07-14 21:10:48.082 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
2024-07-14 21:10:48.082 Error: KIA: conn.request(
2024-07-14 21:10:48.082 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 400, in request
2024-07-14 21:10:48.082 Error: KIA: self.endheaders()
2024-07-14 21:10:48.082 Error: KIA: File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
2024-07-14 21:10:48.082 Error: KIA: self._send_output(message_body, encode_chunked=encode_chunked)
2024-07-14 21:10:48.082 Error: KIA: File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
2024-07-14 21:10:48.083 Error: KIA: self.send(msg)
2024-07-14 21:10:48.083 Error: KIA: File "/usr/lib/python3.9/http/client.py", line 950, in send
2024-07-14 21:10:48.083 Error: KIA: self.connect()
2024-07-14 21:10:48.083 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 238, in connect
2024-07-14 21:10:48.083 Error: KIA: self.sock = self._new_conn()
2024-07-14 21:10:48.083 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 213, in _new_conn
2024-07-14 21:10:48.083 Error: KIA: raise NewConnectionError(
2024-07-14 21:10:48.083 Error: KIA: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x5ce6d0d0>: Failed to establish a new connection: [Errno 111] Connection refused
2024-07-14 21:10:48.083 Error: KIA:
2024-07-14 21:10:48.083 Error: KIA: The above exception was the direct cause of the following exception:
2024-07-14 21:10:48.083 Error: KIA:
2024-07-14 21:10:48.083 Error: KIA: Traceback (most recent call last):
2024-07-14 21:10:48.084 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
2024-07-14 21:10:48.084 Error: KIA: resp = conn.urlopen(
2024-07-14 21:10:48.084 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-07-14 21:10:48.084 Error: KIA: retries = retries.increment(
2024-07-14 21:10:48.084 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment
2024-07-14 21:10:48.084 Error: KIA: raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
2024-07-14 21:10:48.084 Error: KIA: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /json.htm?type=command&param=getdevices&rid=1585 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5ce6d0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-14 21:10:48.084 Error: KIA:
2024-07-14 21:10:48.084 Error: KIA: During handling of the above exception, another exception occurred:
2024-07-14 21:10:48.084 Error: KIA:
2024-07-14 21:10:48.084 Error: KIA: Traceback (most recent call last):
2024-07-14 21:10:48.084 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 805, in getCounter
2024-07-14 21:10:48.085 Error: KIA: response = requests.get(apiCall)
2024-07-14 21:10:48.085 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
2024-07-14 21:10:48.085 Error: KIA: return request("get", url, params=params, **kwargs)
2024-07-14 21:10:48.085 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
2024-07-14 21:10:48.085 Error: KIA: return session.request(method=method, url=url, **kwargs)
2024-07-14 21:10:48.085 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
2024-07-14 21:10:48.085 Error: KIA: resp = self.send(prep, **send_kwargs)
2024-07-14 21:10:48.085 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
2024-07-14 21:10:48.085 Error: KIA: r = adapter.send(request, **kwargs)
2024-07-14 21:10:48.085 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
2024-07-14 21:10:48.085 Error: KIA: raise ConnectionError(e, request=request)
2024-07-14 21:10:48.085 Error: KIA: requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /json.htm?type=command&param=getdevices&rid=1585 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5ce6d0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-14 21:10:48.085 Error: KIA:
2024-07-14 21:10:48.086 Error: KIA: During handling of the above exception, another exception occurred:
2024-07-14 21:10:48.086 Error: KIA:
2024-07-14 21:10:48.086 Error: KIA: Traceback (most recent call last):
2024-07-14 21:10:48.086 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 831, in onHeartbeat
2024-07-14 21:10:48.086 Error: KIA: _plugin.onHeartbeat()
2024-07-14 21:10:48.086 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 328, in onHeartbeat
2024-07-14 21:10:48.086 Error: KIA: self.updateDevices(base, v)
2024-07-14 21:10:48.086 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 729, in updateDevices
2024-07-14 21:10:48.086 Error: KIA: result,Counter,CounterToday=getCounter(TotalPwrConsID)
2024-07-14 21:10:48.086 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 815, in getCounter
2024-07-14 21:10:48.086 Error: KIA: Domoticz.Error(f"ERROR: unable to retrieve the value of device with IDX {varIDX} {response}")
2024-07-14 21:10:48.086 Error: KIA: UnboundLocalError: local variable 'response' referenced before assignment`

What could be wrong?

**Comment by CreasolTech** [comment]
Hi. Please inform me if the error still appear after 24 hours. 
Kia/Hyundai cloud does not provide all required info every time, and maybe you need 1 day to get this problem solved.

**Comment by eekhoorn** [comment]
unfortunately every 4 hour this error:
2024-07-16 16:02:36.806 Error: KIA: Traceback (most recent call last):
2024-07-16 16:02:36.806 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 805, in getCounter
2024-07-16 16:02:36.806 Error: KIA: response = requests.get(apiCall)
2024-07-16 16:02:36.807 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
2024-07-16 16:02:36.807 Error: KIA: return request("get", url, params=params, **kwargs)
2024-07-16 16:02:36.807 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
2024-07-16 16:02:36.807 Error: KIA: return session.request(method=method, url=url, **kwargs)
2024-07-16 16:02:36.807 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
2024-07-16 16:02:36.807 Error: KIA: resp = self.send(prep, **send_kwargs)
2024-07-16 16:02:36.807 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
2024-07-16 16:02:36.807 Error: KIA: r = adapter.send(request, **kwargs)
2024-07-16 16:02:36.807 Error: KIA: File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
2024-07-16 16:02:36.807 Error: KIA: raise ConnectionError(e, request=request)
2024-07-16 16:02:36.807 Error: KIA: requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /json.htm?type=command&param=getdevices&rid=1585 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5d8edac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-07-16 16:02:36.807 Error: KIA:
2024-07-16 16:02:36.807 Error: KIA: During handling of the above exception, another exception occurred:
2024-07-16 16:02:36.807 Error: KIA:
2024-07-16 16:02:36.807 Error: KIA: Traceback (most recent call last):
2024-07-16 16:02:36.807 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 831, in onHeartbeat
2024-07-16 16:02:36.807 Error: KIA: _plugin.onHeartbeat()
2024-07-16 16:02:36.807 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 328, in onHeartbeat
2024-07-16 16:02:36.807 Error: KIA: self.updateDevices(base, v)
2024-07-16 16:02:36.807 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 729, in updateDevices
2024-07-16 16:02:36.807 Error: KIA: result,Counter,CounterToday=getCounter(TotalPwrConsID)
2024-07-16 16:02:36.807 Error: KIA: File "/home/pi/domoticz/plugins/HyundaiKiaConnect/plugin.py", line 815, in getCounter
2024-07-16 16:02:36.807 Error: KIA: Domoticz.Error(f"ERROR: unable to retrieve the value of device with IDX {varIDX} {response}")
2024-07-16 16:02:36.807 Error: KIA: UnboundLocalError: local variable 'response' referenced before assignment

**Comment by CreasolTech** [comment]
The problem seems to be your domoticz not being listen to port 8080. Maybe you're using another port for Domoticz. In this case you can modify the plugin.py file, replacing 8080 with the Domoticz port you're using.

**Comment by eekhoorn** [comment]
Thanks, that's indeed the case. I changed the port and hopefully it is ok now.
