### ISSUE TITLE
No devices are created logs shows connectivity

### ISSUE THREAD

**Issue by JochemLangerak** [CreasolTech/domoticz-hyundai-kia#5]
I'm trying to get the plugin up and running and have updated python, installed several modules, but now i'm facing the following error in domoticz while the logs show connectivity and getting the correct information:

2022-12-28 15:28:30.624 Error: EV6: Call to function 'onHeartbeat' failed, exception details:
2022-12-28 15:28:30.637 Error: EV6: Traceback (most recent call last):
2022-12-28 15:28:30.637 Error: EV6: File "/config/plugins/domoticz-hyundai-kia/plugin.py", line 680, in onHeartbeat
2022-12-28 15:28:30.638 Error: EV6: _plugin.onHeartbeat()
2022-12-28 15:28:30.638 Error: EV6: File "/config/plugins/domoticz-hyundai-kia/plugin.py", line 233, in onHeartbeat
2022-12-28 15:28:30.638 Error: EV6: self.vm.force_refresh_all_vehicles_states() # suggested by P.Levres: fetch data from vehicle to the cloud
2022-12-28 15:28:30.638 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 80, in force_refresh_all_vehicles_states
2022-12-28 15:28:30.638 Error: EV6: self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
2022-12-28 15:28:30.638 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 83, in force_refresh_vehicle_state
2022-12-28 15:28:30.638 Error: EV6: self.api.force_refresh_vehicle_state(self.token, vehicle)
2022-12-28 15:28:30.638 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in force_refresh_vehicle_state
2022-12-28 15:28:30.638 Error: EV6: state = self._get_forced_vehicle_state(token, vehicle)
2022-12-28 15:28:30.638 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 398, in _get_forced_vehicle_state
2022-12-28 15:28:30.638 Error: EV6: return response["resMsg"]["vehicleStatusInfo"]
2022-12-28 15:28:30.638 Error: EV6: KeyError: 'vehicleStatusInfo'

Log:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): prd.eu-ccapi.kia.com:8080
DEBUG:urllib3.connectionpool:https://prd.eu-ccapi.kia.com:8080 "POST /api/v1/user/oauth2/token HTTP/1.1" 200 668
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - Get Refresh Token Response {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5*****************************************zA0MTk0MzZlYzQiLCJ1aWQiOiI0OGE3ZTc0Zi0wYTlkLTQyYTgtYTg2Yi00ZGRhYmFjMDU0OGEiLCJzaWQiOiJmZGM4NWMwMC0wYTJmLT**********************************************jQwOTQsImlhdCI6MTY3MjIzNzY5NCwiaXNz****************************************************pay19r1juy1TgVyvS6LoRual5RhFkMw_Ty7tsW_-Oqz0Mt8sld7qLqIs8ZZT1X4M8CKz40bFph54SPAxtmEwsr3VC78ZcP2p_aZ7aTskBUtrktN1T69jXJhVgG1zZMT6qeilbuozyqnMsEYDnXkcn0A9Hy2h0K6agryuDynpU****************************************8yji13QZmmyTu9DiQnhrUdnw94h4gnnWuaA', 'token_type': 'Bearer', 'expires_in': 86400}
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2022-12-28 13:04:10.396000+00:00 120000 42 998 42.032297191666665
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): prd.eu-ccapi.kia.com:8080
DEBUG:urllib3.connectionpool:https://prd.eu-ccapi.kia.com:8080 "GET /api/v1/spa/vehicles HTTP/1.1" 200 399
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - Get Vehicles Response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicles': [{'vin': 'KNAC***AFN******6', 'vehicleId': 'fb0****f-1***-***d-b**f-c43e*****e7b', 'vehicleName': 'EV6', 'type': 'EV', 'nickname': 'EV6', 'master': True, 'carShare': 0, 'regDate': '2022-09-30 22:28:04.311', 'detailInfo': {'inColor': 'WK', 'outColor': 'B4U', 'saleCarmdlCd': 'AS', 'bodyType': '2', 'saleCarmdlEnNm': 'EV6'}}]}, 'msgId': '2d4bec0f-1371-4609-b125-9179fc83404f'}
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2022-12-28 13:04:10.396000+00:00 120000 42 998 42.033621883333325

**Comment by CreasolTech** [comment]
Did you write the correct VIN ? I just see a very short VIN (maybe you've stripped down the latest part for privacy?)

**Comment by JochemLangerak** [comment]
In the token, VIN and vehicleID I added extra asterisk signs (*), somehow when I click edit I do see these, but not in normal text. Currently I am somewhat further, I compared [KiaUvoApiEU.py](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoApiEU.py) in [https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/) and changed the following code in **_get_forced_vehicle_state**:

```      
        _LOGGER.debug(f"{DOMAIN} - Received forced vehicle data {response}")
        return response["resMsg"]["vehicleStatusInfo"]
```
Into:

```
        _LOGGER.debug(f"{DOMAIN} - Received forced vehicle data {response}")
        mapped_response = {}
        mapped_response["vehicleStatus"] = response["resMsg"]
        return mapped_response
```

Now I do have the devices in Domoticz, but I get the following error in the logs:

2022-12-29 13:00:39.016 Error: EV6: Call to function 'onHeartbeat' failed, exception details:
2022-12-29 13:00:39.021 Error: EV6: Traceback (most recent call last):
2022-12-29 13:00:39.021 Error: EV6: File "/config/plugins/domoticz-hyundai-kia/plugin.py", line 680, in onHeartbeat
2022-12-29 13:00:39.021 Error: EV6: _plugin.onHeartbeat()
2022-12-29 13:00:39.021 Error: EV6: File "/config/plugins/domoticz-hyundai-kia/plugin.py", line 235, in onHeartbeat
2022-12-29 13:00:39.022 Error: EV6: self.vm.update_all_vehicles_with_cached_state() # suggested by P.Levres: download data from the cloud
2022-12-29 13:00:39.022 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
2022-12-29 13:00:39.022 Error: EV6: self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
2022-12-29 13:00:39.022 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
2022-12-29 13:00:39.022 Error: EV6: self.api.update_vehicle_with_cached_state(self.token, vehicle)
2022-12-29 13:00:39.023 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 181, in update_vehicle_with_cached_state
2022-12-29 13:00:39.023 Error: EV6: state = self._get_cached_vehicle_state(token, vehicle)
2022-12-29 13:00:39.023 Error: EV6: File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 348, in _get_cached_vehicle_state
2022-12-29 13:00:39.023 Error: EV6: response = response["resMsg"]["vehicleStatusInfo"]
2022-12-29 13:00:39.023 Error: EV6: TypeError: string indices must be integers

**Comment by CreasolTech** [comment]
What library are you using? 
The original one https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api
or the version modified by jwefers  https://github.com/jwefers/hyundai_kia_connect_api ?
I'm using the lib from jwefers with a Kia eNiro, and python 3.9.2 , but if it does not work it's better that you install the original version so, if it does not work, you can send issue/pull request to the original repository.

**Comment by JochemLangerak** [comment]
I'm using the jwefers version, but changed the code in _get_forced_vehicle_state as described in my previous message.
Using Python 3.9.16. Using the original version I had errors with the time formats %I%M being wrong since I had a "0270" time somewhere in my car status info.
